version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: proyecto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres



  dbt:
    build:
      context: ../avance 3
      dockerfile: Dockerfile
    container_name: dbt-service
    volumes:
      - ../avance 3:/app
    working_dir: /app
    depends_on:
      - postgres
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
