version: 2
models:
- name: stg_fact_ordenes
  description: Staging de la tabla fact_ordenes
  columns:
  - name: orden_id
    description: Identificador de la orden
  - name: usuario_id
    description: Identificador del usuario
  - name: fecha_orden
    description: Fecha en que se realizó la orden
  - name: total
    description: Monto total de la orden
  - name: estado
    description: Estado de la orden
- name: stg_fact_ordenes_metodo_pago
  description: Staging de la tabla fact_ordenes_metodo_pago
  columns:
  - name: id
    description: Identificador del registro
  - name: orden_id
    description: Identificador de la orden
  - name: metodo_pago_id
    description: Método de pago utilizado
  - name: monto_pagado
    description: Monto pagado con este método
- name: stg_fact_detalle_ordenes
  description: Staging de la tabla fact_detalle_ordenes
  columns:
  - name: id
    description: Identificador del detalle
  - name: orden_id
    description: Identificador de la orden
  - name: producto_id
    description: Identificador del producto
  - name: cantidad
    description: Cantidad del producto
  - name: precio_unitario
    description: Precio unitario del producto
- name: ordenes_detalle_completo
  description: Modelo final que une ordenes, métodos de pago y detalles de orden
  columns:
  - name: id
    description: Identificador del detalle
  - name: orden_id
    description: Identificador de la orden
  - name: producto_id
    description: Identificador del producto
  - name: cantidad
    description: Cantidad del producto
  - name: precio_unitario
    description: Precio unitario del producto
  - name: usuario_id
    description: Identificador del usuario
  - name: total
    description: Monto total de la orden
  - name: estado
    description: Estado de la orden
  - name: monto_pagado
    description: Monto pagado
  - name: metodo_pago_id
    description: Método de pago utilizado
- name: fact_historial_pagos
  description: Historial de pagos realizados por los usuarios
  columns:
  - name: id
    description: Identificador del pago
  - name: orden_id
    description: Orden asociada al pago
  - name: metodo_pago_id
    description: Método de pago utilizado
  - name: monto
    description: Monto del pago
  - name: fecha_pago
    description: Fecha del pago
  - name: estado_pago
    description: Estado del pago
- name: dim_productos
  description: Dimensión de productos
  columns:
  - name: producto_id
    description: Identificador del producto
  - name: nombre
    description: Nombre del producto
  - name: descripcion
    description: Descripción del producto
  - name: precio
    description: Precio del producto
  - name: stock
    description: Stock disponible
  - name: categoriaid
    description: Categoría del producto
- name: dim_categorias
  description: Dimensión de categorías de productos
  columns:
  - name: categoria_id
    description: Identificador de la categoría
  - name: nombre
    description: Nombre de la categoría
  - name: descripcion
    description: Descripción de la categoría
- name: fact_resenas_productos
  description: Reseñas realizadas por los usuarios sobre productos
  columns:
  - name: id
    description: Identificador de la reseña
  - name: usuario_id
    description: Usuario que hizo la reseña
  - name: producto_id
    description: Producto reseñado
  - name: calificacion
    description: Calificación otorgada
  - name: comentario
    description: Comentario del usuario
  - name: fecha
    description: Fecha de la reseña
- name: dim_direcciones_envio
  description: Direcciones de envío registradas por los usuarios
  columns:
  - name: direccion_id
    description: Identificador de la dirección
  - name: usuario_id
    description: Usuario asociado
  - name: calle
    description: Calle
  - name: ciudad
    description: Ciudad
  - name: departamento
    description: Departamento
  - name: provincia
    description: Provincia
  - name: distrito
    description: Distrito
  - name: estado
    description: Estado
  - name: codigo_postal
    description: Código postal
  - name: pais
    description: País
- name: fact_carrito
  description: Carrito de compras de los usuarios
  columns:
  - name: id
    description: Identificador del ítem en el carrito
  - name: usuario_id
    description: Usuario que agregó el producto
  - name: producto_id
    description: Producto agregado
  - name: cantidad
    description: Cantidad agregada
  - name: fecha_agregado
    description: Fecha en que se agregó el producto
- name: dim_usuarios
  description: Información de los usuarios registrados
  columns:
  - name: usuario_id
    description: Identificador del usuario
  - name: nombre
    description: Nombre del usuario
  - name: apellido
    description: Apellido del usuario
  - name: dni
    description: Documento de identidad
  - name: email
    description: Correo electrónico
  - name: contrasena
    description: Contraseña
  - name: fecha_registro
    description: Fecha de registro
- name: dim_metodos_pago
  description: Métodos de pago disponibles
  columns:
  - name: metodo_pago_id
    description: Identificador del método de pago
  - name: nombre
    description: Nombre del método de pago
  - name: descripcion
    description: Descripción del método de pago
